name: aqarat
description: Aqarat Developed by Visooft Team.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  dio: ^4.0.4
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  dotted_border: ^2.0.0+3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localization: ^0.1.13
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  # google map
  google_maps_flutter: ^2.2.3
  geolocator: ^10.1.0
  geocoding: ^2.0.5
  # check internet
  internet_connection_checker: ^1.0.0+1
  # otp code field
  pin_code_fields: ^7.4.0
  # translate
  localize_and_translate: ^4.1.2-dev
  shimmer: ^3.0.0
  flutter_native_image: ^0.0.6+1
  image_picker: ^1.0.4
  intl: ^0.18.1
  get: ^4.6.6
  get_it: ^7.6.0
  shared_preferences: ^2.2.1
  flutter_cache_manager: ^3.3.1
  blurry_modal_progress_hud: ^1.1.1
  flutter_spinkit: ^5.2.0
  url_launcher: ^6.1.11
  flutter_slidable: ^3.0.1
  firebase_core: ^2.24.0
  firebase_messaging: ^14.7.6
  awesome_notifications: ^0.8.2
  uuid: ^4.0.0
  permission_handler: ^11.1.0
  logger: ^2.0.2+1
  webview_flutter: ^4.4.2
  share_plus: ^7.2.1
  path_provider: ^2.1.1
  cloud_firestore: ^4.13.6
  





dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/langs/ar.json
    - assets/langs/en.json
  #   - images/a_dot_ham.jpeg
  
   
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700    
        - asset: assets/fonts/NotoSans-Medium.ttf
          weight: 500      
        - asset: assets/fonts/NotoSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/NotoSans-Light.ttf
          weight: 300   
    - family: Horizon
      fonts:
        - asset: assets/fonts/Horizon-Bold.ttf          
    - family: Instrument Serif
      fonts:
        - asset: assets/fonts/InstrumentSerif-Italic.ttf
        - asset: assets/fonts/InstrumentSerif-Regular.ttf
